### ISSUE TITLE
[Unit Test Failure] Unit test `TestUEventListener` fails intermittently

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/directpv#629]
**Describe the bug**
Unit test `TestUEventListener` fails intermittently 

**To Reproduce**
Do not have a reproducer - can be seen in PR github CI runs

**Screenshots and logs**

```
 === RUN   TestUEventListener
panic: test timed out after 10m0s

goroutine 24 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.18.5/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc00011b040, {0x153aaee?, 0x512185?}, 0x15fea20)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc000405440?)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc00011b040, 0xc00015dcd8)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc000364820?, {0x21191c0, 0x16, 0x16}, {0x7fa5566c45b8?, 0x40?, 0x212ff00?})
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc000364820)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:89 +0x1aa

goroutine 22 [chan receive, 10 minutes]:
github.com/minio/directpv/pkg/uevent.(*eventQueue).pop(0xc0004b4018)
	/home/runner/work/directpv/directpv/pkg/uevent/queue.go:100 +0x51
github.com/minio/directpv/pkg/uevent.TestUEventListener(0xc00011bba0)
	/home/runner/work/directpv/directpv/pkg/uevent/listener_test.go:222 +0x11e7
testing.tRunner(0xc00011bba0, 0x15fea20)
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.5/x64/src/testing/testing.go:1486 +0x35f

goroutine 5 [runnable]:
github.com/minio/directpv/pkg/uevent.(*listener).msgPeek(0xc0000a2000, {0x174dc18, 0xc00012c008})
	/home/runner/work/directpv/directpv/pkg/uevent/parse_linux.go:121 +0xf7
github.com/minio/directpv/pkg/uevent.(*listener).readMsg(0xc000541f50?, {0x174dc18, 0xc00012c008})
	/home/runner/work/directpv/directpv/pkg/uevent/parse_linux.go:162 +0x3d
github.com/minio/directpv/pkg/uevent.(*listener).getNextDeviceUEvent(0xc0000a2000, {0x174dc18, 0xc00012c008})
	/home/runner/work/directpv/directpv/pkg/uevent/listener.go:407 +0xc6
github.com/minio/directpv/pkg/uevent.TestUEventListener.func2()
	/home/runner/work/directpv/directpv/pkg/uevent/listener_test.go:118 +0xa9
created by github.com/minio/directpv/pkg/uevent.TestUEventListener
	/home/runner/work/directpv/directpv/pkg/uevent/listener_test.go:112 +0x34c
FAIL	github.com/minio/directpv/pkg/uevent	600.032s
```

**Comment by Praveenrajmani** [comment]
Closing this this is a duplicate of https://github.com/minio/directpv/issues/638
